//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Medium.java
//  @ Date : 4/1/2009
//  @ Author : 
//
//



package edu.fiu.cis.rrcomssys.cvm.mte.xcmlmodel;


/** */
public class Medium
{
    /** */
    public MediumType mediumType;
    
    /** */
    public Action action;
}
