//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MediumApplication.java
//  @ Date : 4/1/2009
//  @ Author : 
//
//



package edu.fiu.cis.rrcomssys.cvm.mte.xcmlmodel;


/** */
public abstract class MediumApplication
{
    /** */
    public String applicationName;
    
    /** */
    public String applicationPath;
    
    /** */
    public void startApplication(String inputFile)
    {
    
    }
}
