//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Text.java
//  @ Date : 4/1/2009
//  @ Author : 
//
//



package edu.fiu.cis.rrcomssys.cvm.mte.xcmlmodel;


/** */
public class Text extends MediumType
{
    /** */
    public String content;
}
