//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : XCMLDocument.java
//  @ Date : 4/1/2009
//  @ Author : 
//
//



package edu.fiu.cis.rrcomssys.cvm.mte.xcmlmodel;

import java.util.List;

import edu.fiu.cis.rrcomssys.cvm.mte.CMLDocument;


/** */
public class XCMLDocument extends CMLDocument
{
    /** */
    public UserDefinition localUser;
    
    /** */
    public List<Connection> connections;
}
