//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AudioFile.java
//  @ Date : 4/1/2009
//  @ Author : 
//
//



package edu.fiu.cis.rrcomssys.cvm.mte.xcmlmodel.media;



/** */
public class AudioFile extends StreamFile
{
}
