//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Device.java
//  @ Date : 4/1/2009
//  @ Author : 
//
//



package edu.fiu.cis.rrcomssys.cvm.mte.xcmlmodel;

import java.util.List;


/** */
public class Device
{
    /** */
    public int deviceId;
    
    /** */
    public List<Capability> capabilities;
}
