//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UserDefinition.java
//  @ Date : 4/1/2009
//  @ Author : 
//
//



package edu.fiu.cis.rrcomssys.cvm.mte.xcmlmodel;


/** */
public class UserDefinition
{
    /** */
    public Person person;
    
    /** */
    public IsAttached isAttached;
    
    /** */
    public Device device;
}
